apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-deployment
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: ansid0cker/bbuy-final-product-service:latest
        ports:
        - containerPort: 80
        env:
        - name: MONGODB_URI
          value: "mongodb://mongodb:27017"
        - name: MONGODB_DATABASE
          value: "product_service"
        - name: MONGODB_COLLECTION
          value: "products"